import {Source} from "react-native-fast-image";

type TbankImg = {
    [key: string]: Source
}

export const bankImg : TbankImg = {
    '한국은행': require('image/payment/bank/한국은행.png'),
    '산업은행': require('image/payment/bank/산업은행.png'),
    '기업은행': require('image/payment/bank/기업은행.png'),
    '국민은행': require('image/payment/bank/국민은행.png'),
    '수협': require('image/payment/bank/수협.png'),
    '한국수출입은행': require('image/payment/bank/한국수출입은행.png'),
    '농협': require('image/payment/bank/농협.png'),
    '농/축협': require('image/payment/bank/농협.png'),
    '우리은행': require('image/payment/bank/우리은행.png'),
    '제일은행': require('image/payment/bank/제일은행.png'),
    '한국씨티은행': require('image/payment/bank/한국씨티은행.png'),
    '대구은행': require('image/payment/bank/대구은행.png'),
    '부산은행': require('image/payment/bank/부산은행.png'),
    '하나은행(충청은행)': require('image/payment/bank/하나은행.png'),
    '광주은행': require('image/payment/bank/광주은행.png'),
    '제주은행': require('image/payment/bank/신한은행.png'),
    '전북은행': require('image/payment/bank/광주은행.png'),
    '경남은행': require('image/payment/bank/부산은행.png'),
    '우리카드': require('image/payment/bank/우리은행.png'),
    '외환카드': require('image/payment/bank/하나은행.png'),
    '새마을금고': require('image/payment/bank/새마을금고.png'),
    '신협': require('image/payment/bank/신협.png'),
    '저축은행': require('image/payment/bank/저축은행.png'),
    '모건스탠리은행': require('image/payment/bank/모건스탠리은행.png'),
    '홍콩상하이은행(HSBC)': require('image/payment/bank/홍콩상하이은행.png'),
    '도이치은행': require('image/payment/bank/도이치은행.png'),
    '유에프제이은행': require('image/payment/bank/유에프제이은행.png'),
    '미즈호코퍼레이트은행': require('image/payment/bank/미즈호코퍼레이트은행.png'),
    '미쓰비시도쿄은행': require('image/payment/bank/유에프제이은행.png'),
    '뱅크오브아메리카': require('image/payment/bank/뱅크오브아메리카.png'),
    '우체국': require('image/payment/bank/우체국.png'),
    '신용보증기금': require('image/payment/bank/신용보증기금.png'),
    '기술신용보증기금': require('image/payment/bank/기술신용보증기금.png'),
    '하나은행': require('image/payment/bank/하나은행.png'),
    '케이뱅크': require('image/payment/bank/케이뱅크.png'),
    '카카오뱅크': require('image/payment/bank/카카오뱅크.png'),
    '토스혁신준비법인': require('image/payment/bank/토스혁신준비법인.png'),
    '동양종합금융증권': require('image/payment/bank/동양종합금융증권.png'),
    '현대증권': require('image/payment/bank/현대증권.png'),
    '미래에셋증권': require('image/payment/bank/미래에셋증권.png'),
    '대우증권': require('image/payment/bank/대우증권.png'),
    '삼성증권': require('image/payment/bank/삼성증권.png'),
    '한국투자증권': require('image/payment/bank/한국투자증권.png'),
    '우리투자증권': require('image/payment/bank/우리은행.png'),
    '교보증권': require('image/payment/bank/교보증권.png'),
    '하이투자증권': require('image/payment/bank/대구은행.png'),
    '투자증권 HMC': require('image/payment/bank/투자증권HMC.png'),
    'SK증권': require('image/payment/bank/SK증권.png'),
    '대신증권': require('image/payment/bank/대신증권.png'),
    '한화증권': require('image/payment/bank/한화증권.png'),
    '하나대투증권': require('image/payment/bank/하나은행.png'),
    '신한금융투자': require('image/payment/bank/신한은행.png'),
    '동부증권': require('image/payment/bank/동부증권.png'),
    '유진투자증권': require('image/payment/bank/유진투자증권.png'),
    '메리츠증권': require('image/payment/bank/메리츠증권.png'),
    'NH 투자증권': require('image/payment/bank/농협.png'),
    '신영증권': require('image/payment/bank/신영증권.png'),
}